- main.go
> Fix typo in comment

- .github/workflows/go.yml
Build against Go 1.13 in Github Actions
> Add go workflow

- .github/workflows/go.yml
- README.md
Replaces the old TravisCI badge.
> Use GitHub Actions badge in README

- README.md
Hello,
today I've made an official formula for `glow` and it got merged to Homebrew: https://github.com/Homebrew/homebrew-core/pull/48916.
This PR aims to mention it in the README.
> Now in Homebrew!

- ui/pager.go
> Remove duplicate "down/j" from the "?" help

- main.go
> Don't handle filenames with a colon in it as http(s) url

- README.md
> Point out the 'glow config' command in README

- main.go
This can be enabled with `-m`/`--mouse` or setting `mouse: true` in the config file. Do note, however, that this currently disables text selection, so _caveat emptor_.
See #206
> Add hidden command/config for enabling mouse wheel support

- README.md
Closes #203
I'm a package maintainer now. :parachute:
> Include installation command for Solus

- go.mod
- go.sum
This supports resolving symlinks when finding documents.
> Bump gitcha to v0.2.0

- go.mod
- go.sum
- ui/stash.go
* Fix pagination when resetting the filter
* Fix inconsistencies when switching between dot and Arabic pager types
Closes #251.
> Fix some filtering and file listing bugs

- ui/ui.go
> Simplify key event handling

- LICENSE
- README.md
This is a tiny PR that makes the README footer consistent with newer Charm repos and updates the date in the LICENSE.
> Update README + License

- .golangci.yml
Switch to revive and drop mnd.
> Update linter config

- README.md
Hi there 👋 
I just noticed that there is an ARM version of glow available for macOS. Maybe this should be mentioned in the README :)
> Mention ARM availability for macOS

- config_cmd.go
> fix: editor with args

- .github/dependabot.yml
> chore: disable dependabot timer

- README.md
I had to experiment a bit until I found the right way to render from stdin. This extended example could be helpful to someone.
> Extend example how to read from stdin

- go.mod
- ui/pager.go
Rebased #388
@bashbunni I tried rebasing but got too many conflicts so this is your PR 
branched off of master.
Authored By: @bashbunni
> feat: copy contents of document

- config_cmd.go
- editor/editor.go
- editor/editor_test.go
- ui/editor.go
> fix: improve editor handling

- ui/pager.go
- ui/stash.go
- ui/stashhelp.go
- ui/ui.go
> feat: add 'r' to refresh list and document

- config_cmd.go
- go.mod
- go.sum
- log.go
- main.go
closes #594
closes #495
closes #328
closes #475
> feat: allow config from CHARM_CONFIG_HOME and XDG_CONFIG_HOME

- main.go
- ui/config.go
- ui/pager.go
> feat: --preserve-new-lines

- main.go
- ui/pager.go
- ui/ui.go
We're using [fsnotify](https://github.com/fsnotify/fsnotify) for this.
This required quite some testing to get right, but I believe it's working reliably!
Let me know if you have any suggestions to improve the implementation, or if you find any bugs. I'll make a couple of comments on the code below.
---
This will close these issues:
- https://github.com/charmbracelet/glow/issues/670
- https://github.com/charmbracelet/glow/issues/135
- https://github.com/charmbracelet/glow/issues/560
- https://github.com/charmbracelet/glow/pull/608
- https://github.com/charmbracelet/glow/pull/427
> feat: watch for file changes and reload automatically

- main.go
- ui/ui.go
> fix: make pipeline for tui work

- ui/pager.go
remove redundant word in comment
> chore: remove redundant word in comment
