main.go
allow `glow *.md` to work by printing all args instead of just the first one :)
=> feat: support multiple files

console_windows.go, go.mod
This ensures ANSI processing is enabled for glow.
=> Enable ANSI for Windows consoles

.github/workflows/go.yml
Fixed workflow syntax, re-enabled Windows tests and removed step for private Go modules.
=> Clean up and re-enable Windows workflow

.github/workflows/lint.yml
Used only for annotation in workflows, currently.
=> Add golangci linter to GitHub workflows

README.md
[scoop](https://github.com/lukesampson/scoop) is a command-line installer for Windows.
by https://github.com/ScoopInstaller/Main/pull/1510, now we could install glow with scoop!
=> Now in Scoop!

main.go, ui/ui.go, utils/utils.go
Fix #146 
This PR adds 2 functions for detecting and removing YAML frontmatter.
Glow will now remove frontmatter from the content right before sending it to Glamour for rendering, it works both on the TUI and CLI.
This code is [adapted from the GitHub CLI](https://github.com/cli/cli/blob/5e89036d49993087b9b45060cc1292a18e1d853a/pkg/githubtemplate/github_template.go#L98).
Demo:
=> Ignore YAML frontmatter

ui/pager.go
`showStatusMessage(statusMessage string)` should display the string passed on the status line. Instead, "Stashed!" is hardcoded as the only string it will ever display. This fixes the behavior to work as intended.
=> Fixed showStatusMessage(statusMessage string)

go.mod, main.go, utils/utils.go
This expands the specified path for the `style` file in the config. Supporting tilde and values from the current environment variables.
Now can specify paths like this:
- `~/.config/glow/style.json`
- `$HOME/.config/glow/style.json`
- `${HOME}/.config/glow/style.json`
Resolves #222
=> Expand the path for a specified style file

main.go, stash_cmd.go, ui/config.go, ui/ui.go
This PR opens a TUI at the given path if the first argument is a directory.
This will open the Glow TUI:
```bash
glow ~
glow ./path/to/whatever
```
But this will attempt to open a markdown file:
```bash
glow ./path/to/README.md
glow github.com/charmbracelet/glow
```
See #234.
=> Open TUI at given path if first argument is a directory

go.mod, go.sum, ui/pager.go
Previously, the status bar in the pager was missing a newline after it, but we didn't notice because terminals were auto-wrapping the following line. The auto-truncating in Bubble Tea v0.12.3 exposed this bug and, thus, this PR adds the missing newline (and bumps deps).
=> Pager rendering correction

README.md
The duplicate docs which this pr removes are the same on stashing with CLI, although the section is about the TUI.
=> Removes duplicate doc about stashing

ui/ui.go
List from GitHub's supported extensions:
- .md
- .markdown
- .mdown
- .mkdn
- .mkd
Fixes #233.
=> Make TUI find markdowns with a variety of file extensions

.goreleaser.yml
- snap config based on https://github.com/tbille/glow-snap
- simplified goreleaser config a bit
- go mod tidy instead of download
- remove unneeded ids/filters
Tested with
```
goreleaser --rm-dist --skip-validate --skip-publish
```
unfortunately it seems impossible to test the actual snap in a docker container... maybe someone with a ubuntu machine can validate?
=> feat: snapcraft packages and improved goreleaser config

.github/workflows/goreleaser.yml
Adds a separate goreleaser workflow, used for building snapshots only (currently).
=> Add goreleaser workflow

ui/ui.go
Otherwise pressing `q` while editing the filter will quit glow.
=> Pass through all keys when editing filter

.github/workflows/lint.yml
Specifying a version is now optional in golangci-lint-action.
=> Always use latest version of golangci-lint

.github/workflows/goreleaser.yml
Prevents this workflow from failing when running in the PR-context, as the secrets aren't available.
=> Only login to snapcraft when secret is available in goreleaser workflow

go.mod, main.go
The golang.org/x/crypto/ssh/terminal package is deprecated and merely a
wrapper around golang.org/x/term. Use the latter directly and avoid a
direct dependency on the former.
=> Use golang.org/x/term

.goreleaser.yml
copied from meta
eventually we should refactor this to use meta :)
fixes https://github.com/charmbracelet/glow/runs/7254764701?check_suite_focus=true
=> fix: goreleaser workflow

main.go
As already discussed in https://github.com/charmbracelet/glow/issues/329
the exit message can be a bit irritating, especially when integrating
glow into scripts/etc.
PR https://github.com/charmbracelet/glow/pull/331 did more than just
remove the exit message but was since closed by the requestor.
=> Remove exit message

config_cmd.go
Resolves #380 
Use the `filepath` implementation of `Dir` instead of `path`. Resolve path resolution with Windows paths containing `\\` separators.
Given a `configFile` value of `"C:\\Users\\Christopher\\AppData\\Local\\glow\\Config\\glow.yml"`, `path.Dir(configFile)` resolves to a value of `"."`.
Looks like a difference in how path separators are handled by `path.Dir` and `filepath.Dir`. See https://groups.google.com/g/golang-nuts/c/UoRlbaSqtDk for additional info.
=> fix: use filepath.Dir instead of path.Dir

README.md
Add a note to just use `go install` for installation.
Perhaps obvious, but I tend to simply use go as a package manager for golang projects.
Edit: Also, this is just super nice; been looking for a good terminal markdown viewer and this renders beautifully, thanks!
=> docs: streamline install instructions

ui/editor.go, ui/pager.go, ui/stash.go
Fixes https://github.com/charmbracelet/glow/issues/182
Introduce key binding to allow users to open their `EDITOR` to edit local
markdown files in stash and pager view.
=> Open Local Markdown Files in `EDITOR`

main.go
This PR fixes an issue with the latest `glow` which double closes the response
body which prevents it from reading HTTPS links.
The `sourceFromArgs` closes the https response body and provides the body to the `source` which also closes it.
```
defer src.reader.Close()
```
This PR removes the initial closing so that the `source` can be read and
closed.
=> Fix double close body

ui/pager.go, ui/stash.go, ui/stashhelp.go
- fix: only show edit help on pager when editable
- fix: only allow `LocalDoc`s to be edited
- feat: show e • edit help when document is editable
=> Show edit help in stash model

go.mod, go.sum
This update fixes performance scrolling by way of the latest Bubbles release: [`v0.15.0`](https://github.com/charmbracelet/bubbles/releases/tag/v0.15.0). Prior to this update performance scrolling had compromised performance.
For details see: https://github.com/charmbracelet/bubbles/pull/312
=> fix: performance scrolling

main.go
Fixes #212 based on @fiskhest's [comment](https://github.com/charmbracelet/glow/issues/212#issuecomment-921632355).  
Updated glamour version and added a line in `main.go` to preserve line breaks.  
```
$ cat test.md
two spaces  
break tag<br>
backslash\
hello world
```
```
$ glow test.md
two spaces break tag backslash hello world
```
```
$ go build
$ ./glow test.md
two spaces
break tag
backslash
hello world
```
=> fix: support hard line breaks

ui/stash.go
paginator.NewModel is deprecated in favor of New
=> fix: do not use deprecated func

ui/markdown.go, ui/pager.go, ui/stash.go, ui/stashhelp.go, ui/stashitem.go, ui/styles.go, ui/ui.go
Found via `typos --format brief`
=> docs: fix typos

main.go
For large input files, the string concatenation in a hot loop done to trim lines is a bottleneck, running in quadratic time since it has to copy the current string every time. Using a string builder, this can be optimized in linear time.
For Minetest's large [`lua_api.md`](https://github.com/minetest/minetest/blob/master/doc/lua_api.md), this brings the time down from 45s to 3s, a 15x speedup, on my laptop.
=> Replace string concatenation in loop with string builder

config_cmd.go, editor/editor.go, editor/editor_test.go, ui/editor.go
snaps have a myriad of `SNAP_.*` env vars set, so I see if one of them is present (in which case we are sandboxed, and can't really open an EDITOR) and error out to the user suggesting installing it some other way.
=> fix: handle running inside a snap

main.go
glamour was ignoring the detected color profile when running `glow file.md`
=> fix: pass color profile down to glamour

README.md, config_cmd.go, main.go
=> Make --all configurable globally

ui/stash.go, ui/stashhelp.go, ui/ui.go
Removing some more artifacts of the remote stash feature that were left behind.
On a side note: eventually, we should probably rename 'stash' to something else internally, as of now the old name is still being used.
=> fix: remove more stash-related stuff

ui/ui.go
Fixes #644 
First of all, thank you for this tool! Great fun to use. I was a bit annoyed by it triggering a reload when I'm inputting a filter. To fix it I just copied the way in which this was done from the `q` key. If you want it done differently or have another fix in the works, let me know!
=> Enable "r" in filter state

ui/stashhelp.go
I found this while working on an unrelated issue. There was not hint for `e`/ `edit` at all.
=> fix: restore hint for `e` / `edit` on the footer

main.go, ui/config.go, ui/ui.go
We had two possible paths to address this:
- Add a new `--tui` / `-t` flag
- Add a new `--mode` flag with `pager`/`tui`/`none` as possible values
Having a `--tui` flag felt a bit more reasonable to me because:
- The `-m` shortant is already taken by `--mouse` while `-t` is available. (We could of course use `-M` though).
- This avoids the need to deprecate `--pager` / `-p`.
Happy to change if you find better, though.
Let me know if you find any bugs while testing.
---
This will close the following issues:
- https://github.com/charmbracelet/glow/issues/129
- https://github.com/charmbracelet/glow/issues/489
- https://github.com/charmbracelet/glow/issues/535
- https://github.com/charmbracelet/glow/pull/548
=> feat: add new `--tui` / `-t` flag

ui/ui.go
* last PR changed 'strings.ReplaceAll' to 'filepath.Rel'
* but still did not handle (or think about) symlink well
=> fix: correct path strip

ui/pager.go
Closes #733 
Follows the guidelines in https://github.com/fsnotify/fsnotify?tab=readme-ov-file#watching-a-file-doesnt-work-well to watch the files parent directory instead of the file itself.
Tested on both mac and Linux (Arch). On mac it seems like only the CREATE event will come through followed by a few others. On Linux it will be a CREATE followed by a WRITE. In both cases watching the parent directory makes sure any CREATE events don't have an impact on the watched file.
Might end up with more frequent reloads but I haven't dug into it that much.
=> fix: watch for write+create changes on file parent

main.go, url.go
When using the -t flag with a remote URL, Glow was trying to treat the URL as a local file path. 
This change fixes the issue by only passing the path parameter to the TUI when dealing with local files, and passing just the content for remote URLs. 
Fixes #719 
- Remote raw URLs: `glow -t https://raw.githubusercontent.com/charmbracelet/glow/refs/heads/master/README.md`
- GitHub repository URLs: `glow -t https://github.com/charmbracelet/glow`
- GitLab repository URLS: `glow -t https://gitlab.com/interception/linux/plugins/caps2esc`
- Local markdown files: `glow -t README.md`
=> fix: TUI mode handling of remote URLs

ui/pager.go
Refreshes the `viewport` on `HalfViewDown`/`HalfViewUp` similar to `GoToTop` and `GoToBottom`.
I was able to replicate the linked issue and confirms this fixes it (for me at least).
This is the text I used to replicate the issue
```md
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Here is
some example
text.
To help
illustrate
my issue.
These
Lines
*Adding a code block*
```C
int main() {
int x = 0;
return 0;
}
```end
Might
Be
Duplicated
```
Output of `kitty +kitten query_terminal` that I tested with
```
name: kitty
version: 0.41.1
allow_hyperlinks: yes
font_family: IosevkaNFM
bold_font: IosevkaNFM-SemiBold
italic_font: IosevkaNFM-Italic
bold_italic_font: IosevkaNFM-SemiBoldItalic
font_size: 16
dpi_x: 192
dpi_y: 192
foreground: #f8f8f2
background: #272822 …
```
=> fix: sync viewport on half page up/down to prevent duplicate strings

ui/stash.go, ui/stashhelp.go
Hello,
currently, attempting to edit with no files present causes the app to crash because m.selectedMarkdown() returns nil, which leads to a runtime error when it is passed to openEditor().
- [handle case when selected md is nil, which led to the crash](https://github.com/charmbracelet/glow/commit/b49e1931aaf643ca0aba76564e7c8dc33d721178) 
(tea.Batch seems to handle it gracefully now.)
- [only show edit help if documents are available](https://github.com/charmbracelet/glow/commit/2a4725cade2d9649f932b6e199b458551b78fcb7)
New empty state:
Documents present:
I also created a [version](https://github.com/MarkusBillharz/glow/compare/task/fix_edit_crash_on_empty_stash...MarkusBillharz:glow:task/create_file_if_stash_is_empty) on top of this fix that points to a default file instead, but wasn’t …
=> Fix: prevent crash on edit attempt with no files present
